server:
  port: 8080

spring:
  application:
    name: class-quest
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    format:
      date: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://<HOST>:<PORT>/classquest?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: classquest
    password: classquest
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: <HOST>
      port: 6379
      timeout: 10s
      lettuce:
        pool:
          max-active: 100
          max-wait: 100ms
          max-idle: 3
          min-idle: 0
      password:

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  mail:
    host: smtp.qq.com
    port: 465
    username: 40505282@qq.com
    password:
    test-connection: true
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          ssl:
            enable: true

sa-token:
  token-name: authorization
  timeout: 604800
  active-timeout: -1
  is-concurrent: true
  is-share: false
  token-style: simple-uuid
  isReadHeader: true
  isReadCookie: false

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '基于springboot,aigc 的数字化教学平台系统'
      paths-to-match: '/**'
      packages-to-scan: cn.org.shelly.edu.controller

knife4j:
  enable: true
  setting:
    language: zh_cn

logging:
  level:
    cn.org.shelly: debug

thread:
  pool:
    core-pool-size: 5
    max-pool-size: 10
    queue-capacity: 50
    keep-alive-seconds: 60
